In [11]:
# Libraries needed for the tutorial

import pandas as pd
import requests
import io
import json
from pandas import json_normalize


url ='https://services6.arcgis.com/Bd4MACzvEukoZ9mR/arcgis/rest/services/county_MOHSIS_map/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json'
response = requests.get(url).json()
#print(json.dumps(response, indent=4, sort_keys=True))
df = json_normalize(response, 'features')
#df.columns = df.columns.str.replace(r'_x$', '')
#df.rename(columns = lambda x: x.strip('attributes.'))
df.columns = [col.replace('attributes.', '') for col in df.columns]
#df.head(30)

In [12]:
county_df = pd.read_csv("../Missouri_Counties.csv")
county_df2 = county_df[county_df.columns[1:5]]
#county_df2.head()

In [16]:
#df['NAME2'] = df['NAME2'].astype(str)
#county_df2['NAME2'] = county_df2['NAME2'].astype(str)
#df.join(county_df2, on='NAME2')
df_final=df.merge(county_df2, left_on='NAME2', right_on='NAME2')
df_final.head()

,OBJECTID,NAME,NAME2,CASES,DEATHS,Shape__Area,Shape__Length,GlobalID,CreationDate,Creator,EditDate,Editor,geometry.rings,CNTY_FIPS,FIPS,COUNTYGNIS
0,2224,Adair,ADAIR,292,0,1.473390e+09,155251.053818,d63c9a2c-216e-4e32-92c3-c04fb2a2ea73,1600109015000,mophep,1600109015000,mophep,"[[[-92.3478208840285, 40.302804629629], [-92.3...",1,29001,765805
1,2225,Andrew,ANDREW,187,1,1.130287e+09,163786.567767,1927484c-6fa6-4f9e-a9bd-910cb1637fed,1600109015000,mophep,1600109015000,mophep,"[[[-94.6059390844084, 40.1261753038853], [-94....",3,29003,758456
2,2226,Atchison,ATCHISON,41,0,1.418004e+09,188930.314765,eac8d9bc-406f-4744-b5f5-df503e84e5af,1600109015000,mophep,1600109015000,mophep,"[[[-95.2024414996767, 40.5784663769025], [-95....",5,29005,758457
3,2227,Audrain,AUDRAIN,371,2,1.803689e+09,215719.629416,d934afc7-bb5c-4ded-b13f-9fc4c01b3c2d,1600109016000,mophep,1600109016000,mophep,"[[[-91.7179813406387, 39.3391363676128], [-91....",7,29007,758458
4,2228,Barry,BARRY,410,5,2.047063e+09,183363.850208,2bf3c157-f782-4e3c-8a32-b4828a183d2a,1600109016000,mophep,1600109016000,mophep,"[[[-93.6110169618323, 36.9228443060673], [-93....",9,29009,758459